<?php
/**
 * Demo my custom theme inherit Magento's Luma theme.
 *
 *  @var $block Magento\Framework\View\Element\Template 
 */
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare no-display" title="<?= $block->escapeHtmlAttr(__('Compare Products')) ?>"
       data-bind="attr: {'href': compareProducts().listUrl}"
    >
        <?= $block->escapeHtml(__('Compare')) ?>
        <span class="counter qty" data-bind="text: parseInt(compareProducts().countCaption) || 0"></span>
    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>
